# Generated by Django 3.0.5 on 2020-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.PositiveIntegerField(unique=True, verbose_name='Id города')),
                ('icon', models.URLField(verbose_name='Картинка погоды')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('description', models.CharField(max_length=100, verbose_name='Погодные условия')),
                ('temp', models.FloatField(verbose_name='Температура')),
                ('pressure', models.PositiveSmallIntegerField(verbose_name='Атмосферное давление')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Влажность воздуха')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='Скорость ветра')),
                ('coord_lon', models.FloatField(verbose_name='Географические координаты - долгота')),
                ('coord_lat', models.FloatField(verbose_name='Географические координаты - широта')),
                ('sunrise', models.TimeField(verbose_name='Восход')),
                ('sunset', models.TimeField(verbose_name='Закат')),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погода',
            },
        ),
    ]
