# Generated by Django 3.0.5 on 2020-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('city_id', 'Id города: по возростанию'), ('-city_id', 'Id города: по убыванию'), ('name', 'Имя: по возростанию'), ('-name', 'Имя: по убыванию'), ('temp', 'Температура: по возростанию'), ('-temp', 'Температура: по убыванию')], default='city_id', max_length=10)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['name'], 'verbose_name': 'Погода', 'verbose_name_plural': 'Погода'},
        ),
    ]
