# Generated by Django 3.0.5 on 2020-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='ID города'),
        ),
    ]
