# Generated by Django 3.0.5 on 2020-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_cities', '0002_auto_20200406_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Погода', 'verbose_name_plural': 'Погода'},
        ),
        migrations.AlterField(
            model_name='ordering',
            name='sort',
            field=models.CharField(choices=[('city_id', 'Id города: по возростанию'), ('-city_id', 'Id города: по убыванию'), ('name', 'Имя: по возростанию'), ('-name', 'Имя: по убыванию'), ('temp', 'Температура: по возростанию'), ('-temp', 'Температура: по убыванию')], default='city_id', max_length=10, verbose_name='Сортировать по:'),
        ),
    ]
