# Generated by Django 3.0.5 on 2020-04-07 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather_cities', '0004_weather_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='user',
        ),
        migrations.AddField(
            model_name='weather',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
