# Generated by Django 3.0.5 on 2020-04-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_cities', '0005_auto_20200407_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city_id',
            field=models.PositiveIntegerField(verbose_name='Id города'),
        ),
    ]
